/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Shedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    JsonElement getJsonElementFromDatabase(String pth) {
        try {
            //URL u = new URL(pth);
            FileInputStream in = new FileInputStream(pth);
            InputStreamReader inr = new InputStreamReader(in);
            JsonParser jp = new JsonParser();
            JsonElement je = jp.parse(inr);
            in.close();
            inr.close();
            return je;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String pth = "data.json";                   //Shedule Watering
            JsonElement je = getJsonElementFromDatabase(pth);
            JsonObject root = je.getAsJsonObject();
            JsonArray crop = root.getAsJsonArray("crops");
            Iterator<JsonElement> it = crop.iterator();

            while (it.hasNext()) {
                JsonObject obj = it.next().getAsJsonObject();

                int frequent_day = obj.get("frequent_days").getAsInt();
                String mid = obj.get("motor").getAsString();

                String mCode = "";
                double mFlowRate = 0.0;
                int mAngle = 0;

                JsonArray motors = root.getAsJsonArray("motors");
                Iterator<JsonElement> iter_m = motors.iterator();
                while (iter_m.hasNext()) {
                    JsonObject obj1 = iter_m.next().getAsJsonObject();
                    String x = obj1.get("m_id").getAsString();;
                    if (x.equals(mid)) {
                        mCode = obj1.get("m_code").getAsString();
                        mFlowRate = obj1.get("flowrate").getAsDouble();
                        mAngle = obj1.get("m_angle").getAsInt();
                        break;
                    }
                }
                JsonArray water = obj.get("water").getAsJsonArray();
                System.out.println(water);
                Iterator<JsonElement> iter_c = water.iterator();
                while (iter_c.hasNext()) {
                    JsonObject obj1 = iter_c.next().getAsJsonObject();
                    int litre = obj1.get("litre").getAsInt();
                    String time= obj1.get("time").getAsString();
                    
                    int delay= (int)(litre/mFlowRate);           //Calculation Time by Q=V/t equation
                    
                    Calendar c=new GregorianCalendar();
                    String date=c.get(Calendar.YEAR)+"-"+(c.get(Calendar.MONTH)+1)+"-"+c.get(Calendar.DAY_OF_MONTH)+" "+time+":00";
                   
                    String cStart=mCode+String.format("%03d", mAngle);
                    String cStop=mCode+"000";
                    
                    
                    
                    //call shedule function
                }

               
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
